const E=GroundNodeEncounter,$=id=>document.getElementById(id);let state=E.create(),paused=false,perspective='pilot',view=null,last=performance.now(),uiAt=0,messageKey='';
function execute(command){const result=E.command(state,command);$('pilotNotice').textContent=result.ok?'Action recorded in the shared conversation.':result.reason;update();}
const actions={requestLanding:'requestLanding',acceptReservation:'accept',declineReservation:'unable',engageFlight:'fly',requestDeparture:'requestDeparture',reconnect:'reconnect'};
for(const [id,c] of Object.entries(actions))$(id).onclick=()=>execute(c);
$('clearPad').onclick=()=>execute('obstruction');$('linkFault').onclick=()=>execute(E.aircraft(state).connected?'disconnect':'reconnect');
$('pauseEncounter').onclick=()=>{paused=!paused;$('pauseEncounter').textContent=paused?'Resume':'Pause';};
$('restartEncounter').onclick=()=>{state=E.create();paused=false;messageKey='';$('pauseEncounter').textContent='Pause';$('pilotNotice').textContent='Demo preflight checks are preset. Pilot acceptance does not engage flight guidance.';update();};
document.querySelectorAll('[data-perspective]').forEach(b=>b.onclick=()=>{perspective=b.dataset.perspective;document.querySelectorAll('[data-perspective]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update();});
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{view?.setCamera(b.dataset.camera);document.querySelector('.scene-shell').classList.toggle('seat-view',b.dataset.camera==='cockpit');document.querySelectorAll('[data-camera]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
$('exportEncounter').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({scenario:'vahnim-one-pad',simulated:true,aircraft:E.aircraft(state),position:state.pos,messages:state.link.messages},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='vahnim-shared-encounter.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function readout(){const a=E.aircraft(state),r=a.reservation;
 if(!a.connected)return {title:'Connection lost.',text:'Reservation invalidated. The simulated aircraft returns to its holding position. Reconnect and request again.',status:'Link lost'};
 if(state.complete)return {title:'Departure complete.',text:'VH-101 is clear of the pad. GroundNode has released the reservation.',status:'Complete'};
 if(r)return {title:r.operation==='landing'?'Landing reservation.':'Departure reservation.',text:r.status==='sent'?'GroundNode has sent an offer. Awaiting simulated delivery.':r.status==='received'?'GroundNode has checked the pad and approach. Accept or decline this reservation.':state.engaged?'Pilot engaged simulated flight guidance. Aircraft reports will follow its 3D movement.':'Reservation accepted. Engage simulated flight guidance separately when ready.',status:r.status};
 if(a.phase==='landed'||a.phase==='servicing')return {title:a.phase==='servicing'?'Ready on the pad.':'Touchdown confirmed.',text:a.phase==='servicing'?'Propulsion-safe report received. Request departure when ready.':'GroundNode recorded touchdown. Simulated propulsion is winding down before service.',status:a.phase};
 if(a.phase==='requestSent'||a.phase==='requested')return {title:'Request processing.',text:'GroundNode is checking current pad status and the approach sector automatically.',status:a.phase==='requestSent'?'Sent':'Received'};
 if(a.phase==='holding')return {title:'Hold position.',text:state.link.blocked?'Pad obstruction detected. GroundNode is monitoring your open request; it will reassess when the obstruction is removed.':state.intent?'The pad is clear. GroundNode is reassessing your request.':'No active reservation. Submit a new request when ready.',status:'Hold'};
 return {title:'Request your arrival.',text:'GroundNode is connected and ready. Send a landing request to begin the encounter.',status:'Ready'};
}
function update(){const a=E.aircraft(state),r=a.reservation,info=readout(),ground=perspective==='ground';
 $('displayContext').textContent=ground?'GN-01 / ground supervisor':'VH-101 / cockpit display';$('endpointLabel').textContent=ground?'GROUND SUPERVISOR':'AIRCRAFT CLIENT';$('endpointName').textContent=ground?'GN-01 ↔ VH-101':'VH-101 → GN-01';$('screenMode').textContent=ground?'SHARED SESSION · HUMAN OVERSIGHT':'PILOT DECISIONS · AUTOMATIC GROUND RESPONSES';
 $('pilotActions').hidden=ground;$('groundReview').hidden=!ground;$('groundDecision').textContent=info.text;$('instructionType').textContent=r?.id||'GN LINK';$('instructionStatus').textContent=info.status.toUpperCase();$('instructionTitle').textContent=info.title;$('instructionText').textContent=info.text;$('validity').textContent=r?Math.max(0,Math.ceil(r.expires-state.link.now))+' s remaining · '+(r.status==='accepted'?'operation window':'response window'):'';
 $('linkState').textContent=a.connected?'Connected':'Link lost';$('clock').textContent=new Date(state.link.now*1000).toISOString().slice(14,19);$('altitude').textContent=state.pos.y.toFixed(1)+' m';$('speed').textContent=Math.hypot(state.vel.x,state.vel.y,state.vel.z).toFixed(1)+' m/s';$('padCondition').textContent=state.link.blocked?'Obstructed':state.link.occupant?'Occupied':'Clear';
 $('flightPhase').textContent=state.complete?'Departed':state.engaged?(state.stage==='descend'?'Descending':state.stage==='launch'?'Climbing':state.stage==='outbound'?'Departing':'Approaching'):state.link.occupant?'On pad':'Holding';$('sceneStatus').textContent=state.link.blocked?'Synthetic inspection: obstruction':state.link.occupant?'Touchdown confirmed':'Synthetic inspection: pad clear';
 $('requestLanding').disabled=!a.connected||!!r||state.complete||!['connected','holding'].includes(a.phase)||!!state.intent;$('requestDeparture').disabled=!a.connected||!['landed','servicing'].includes(a.phase)||!!r||!!state.intent;
 $('acceptReservation').disabled=r?.status!=='received';$('declineReservation').disabled=r?.status!=='received';$('engageFlight').disabled=!['authorized','departureAuthorized'].includes(a.phase)||state.engaged;$('engageFlight').textContent=a.phase==='departureAuthorized'?'Start simulated departure':'Start simulated approach';$('reconnect').disabled=a.connected;
 $('clearPad').textContent=state.link.blocked?'Remove obstruction':'Add obstruction';$('linkFault').textContent=a.connected?'Simulate link loss':'Restore demo link';
 const key=state.link.seq+'|'+state.link.messages.map(m=>m.status).join(',');if(key!==messageKey){messageKey=key;$('eventCount').textContent=state.link.messages.length+' events';$('encounterMessages').replaceChildren(...state.link.messages.slice(-40).reverse().map(m=>{const div=document.createElement('div');div.className='message'+(m.direction==='aircraft → node'?' air':'');const meta=document.createElement('div');meta.className='message-meta';const label=document.createElement('span'),badge=document.createElement('span');label.textContent='#'+m.id+' · '+m.at.toFixed(1)+'s · '+m.direction;badge.className='message-status';badge.textContent=m.status;meta.append(label,badge);const text=document.createElement('p');text.textContent=m.type+' · '+m.text;div.append(meta,text);return div;}));}
}
update();try{const {createEncounterRenderer}=await import('./encounter-renderer.js');view=createEncounterRenderer($('encounterCanvas'));}catch(error){$('sceneError').hidden=false;console.error(error);}
function frame(now){const dt=Math.max(0,Math.min(.08,(now-last)/1000));last=now;if(!paused&&!document.hidden)E.advance(state,dt);if(!document.hidden)view?.draw(state,paused?0:dt,readout());if(now-uiAt>150){update();uiAt=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>last=performance.now());

