const assert=require('node:assert/strict');require('./coordination.js');require('./encounter.js');const E=GroundNodeEncounter;
function advance(s,seconds){for(let t=0;t<seconds;t+=1/60){const old={...s.pos};E.advance(s,1/60);assert(Object.values(s.pos).every(Number.isFinite));assert(s.pos.y>=0);assert(Math.hypot(s.pos.x-old.x,s.pos.y-old.y,s.pos.z-old.z)<.2,'Bounded per-step motion');}}
let s=E.create();assert(E.command(s,'requestLanding').ok);advance(s,3);assert.equal(E.aircraft(s).phase,'holding');assert.equal(s.link.occupant,null);E.command(s,'obstruction');advance(s,4);assert.equal(E.aircraft(s).reservation.status,'received','Ground automatically reassesses and offers');E.command(s,'accept');advance(s,2);assert.equal(s.engaged,false,'Acceptance does not engage flight');assert.equal(s.pos.y,30);E.command(s,'fly');advance(s,70);assert.equal(E.aircraft(s).phase,'servicing');assert.equal(s.link.occupant,'VH-101');assert.equal(s.pos.y,0);
E.command(s,'requestDeparture');advance(s,4);E.command(s,'accept');E.command(s,'fly');advance(s,65);assert(s.complete);assert.equal(s.link.occupant,null);
s=E.create();E.command(s,'obstruction');E.command(s,'requestLanding');advance(s,4);E.command(s,'accept');E.command(s,'fly');advance(s,18);E.command(s,'obstruction');advance(s,35);assert.equal(s.link.occupant,null);assert.equal(s.engaged,false);assert(s.pos.y>29);
E.command(s,'obstruction');advance(s,4);E.command(s,'accept');E.command(s,'disconnect');advance(s,2);assert.equal(E.aircraft(s).reservation,null);assert.equal(s.intent,null);
s=E.create();E.command(s,'obstruction');E.command(s,'requestLanding');advance(s,4);E.command(s,'unable');advance(s,8);assert.equal(E.aircraft(s).reservation,null,'Declining must not automatically reoffer');
s=E.create();E.command(s,'obstruction');E.command(s,'requestLanding');advance(s,40);assert.equal(E.aircraft(s).reservation,null);assert.equal(s.intent,null,'Expiry needs a new pilot request');
console.log('PASS: automatic hold/reassessment, explicit pilot engagement, 3D arrival/service/departure, hazard recovery, decline and expiry.');
